server:
  servlet:
    context-path: /
  port: 5000
spring:
  application:
    name: service--payment
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    banner-mode: 'OFF'
  config:
    import: "configserver:${CONFIG_SERVER:http://localhost:8888/config/}"
  cloud:
    allow-override: true
    config:
      username: develop
      password: develop
      name: "service--payment"
      label: master
    retry:
      max-attempts: 5000
      initial-interval: 1500
      multiplier: 1.5
      compatibility-verifier:
        enabled=false:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: ${SPRING_JPA_TIMEZONE:America/Sao_Paulo}
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    tomcat:
      max-active: ${SPRING_DATASOURCE_MAX_ACTIVE:10}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/dbpayment?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
  rabbitmq:
    username: "admin"
    password: "passw123"
    port: 5672
    host: localhost

info:
  app:
    name: "@project.name@"
    version: "@project.version@"
    description: "@project.description@ "
    base-package: "com.shoesclick.service.payment"

rabbitmq:
  exchange: shoesclick_exchange
  notification:
    queue: mq_notification
    routingKey: notification_routingkey
  payment:
    queue: mq_payment
    routingKey: payment_routingkey

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    prefer-ip-address: 'true'

management:
  server:
    port: 9090
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, shutdown, prometheus
  endpoint:
    shutdown:
      enabled: true
      health:
        show-details: always
        probes:
          enabled: true
        group:
          readiness:
            include: diskSpace

opentracing:
  service-name: bff-site-shoes-app
  jaeger:
    http-sender:
      url: ${JAEGER_HOST:http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces