apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service--payment-hpa
  namespace: shoes-eks
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service--payment-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  