apiVersion: v1
kind: Service
metadata: 
  name: svc-service--payment
  namespace: shoes-eks
spec:
  type: ClusterIP
  selector:
      app: service--payment
  ports:
    - port: 5000
      name: http-5000
      protocol: TCP
      targetPort: 5000
    - port: 9190
      name: http-prometheus
      protocol: TCP
      targetPort: 9190